Added Pinterest Authenticator
wso2-extensions/identity-outbound-auth-pinterest pull request #1
Opened 2017-03-31 09:30 UTC by vives

2017-04-19 10:21 UTC, ruwanta requested changes

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +		callbackUrl.setDescription("Enter value corresponding to callback url.");
--> Enter value corresponding to callback URL.

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +				throw new AuthenticationFailedException("Authenticator Properties cannot be null");
--> Authenticator Properties obtained from the  AuthenticationContext is null

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +						throw new AuthenticationFailedException("Selected user profile not found");
-->Claims for the user not found for access Token : "+ accessToken

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +						throw new AuthenticationFailedException("Selected user profile not found");
Always have identifiable information on any exception thrown, so that someone going through logs can see exactly which object went on error.

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			URL obj = new URL(url + PinterestAuthenticatorConstants.QUESTION_MARK +
Usually "?" and "=" can be present in the string itself. We do not need them to be constants. There is no performance or readability or any harm.

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			URLConnection connection = obj.openConnection();
Better to set some timeout ,
e.g.
connection.setConnectTimeout(connectTimeout);
connection.setReadTimeout(socketTimeout);

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("Exception while generating the user info URL", e);
put the context information in the exception, e.g URL, accessToken, etc.

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			json = getUserInfo(url, accessToken);
Better to return JSONObject 
Better to change the method name to fetchUserInfo(..) or queryUserInfo(..)

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			Map<String, Object> jsonObject = JSONUtils.parseJSON(userData);
Why 
String userData = json.toString()
and then
JSONUtils.parseJSON(userData);
This heavy on performance (CPU and memory)

We should be able to traverse the JSON DOM itself the get them.

2017-04-19 10:21 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +	private void setSubjectFromClaims(AuthenticationContext context, String subjectFromClaims,
change this to associateSubjectFromClaims

2017-04-21 09:38 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("ProtocolException while setting the request method: " +
Need to put the URL on the error message too.  There is no real value of an error log such as 
"ProtocolException while setting the request method: POST" without the offending URL.

2017-04-21 09:40 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +		StringBuilder stringBuilder = new StringBuilder();
stringBuilder --> jsonResponseCollector

2017-04-21 09:41 UTC, ruwanta commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +					throw new AuthenticationFailedException("Authentication Failed, access token is not available");
Always we have to say or indicate the access token which causes the error.

2017-04-25 09:49 UTC, vives commented on component/pom.xml
> +                            org.wso2.carbon.identity.application.authentication.framework.*,
fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:49 UTC, vives commented on component/pom.xml
> +                            org.apache.oltu.oauth2.*;
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:49 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticatorConstants.java
> +public class PinterestAuthenticatorConstants {
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:50 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/internal/PinterestAuthenticatorServiceComponent.java
> +     * activate custom authenticator.
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:50 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/internal/PinterestAuthenticatorServiceComponent.java
> +        } catch (Throwable e) {
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:50 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +		callbackUrl.setDescription("Enter value corresponding to callback url.");
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +				throw new AuthenticationFailedException("Authenticator Properties cannot be null");
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +						throw new AuthenticationFailedException("Selected user profile not found");
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			URL obj = new URL(url + PinterestAuthenticatorConstants.QUESTION_MARK +
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			URLConnection connection = obj.openConnection();
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("Exception while generating the user info URL", e);
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			json = getUserInfo(url, accessToken);
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:51 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			Map<String, Object> jsonObject = JSONUtils.parseJSON(userData);
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/2d20b214a60d365dbfdad4f646691e271a536769

2017-04-25 09:52 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("ProtocolException while setting the request method: " +
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/9677bf19d79c461d484e61e2bf3c9332c6305ef6

2017-04-25 09:52 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +		StringBuilder stringBuilder = new StringBuilder();
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/9677bf19d79c461d484e61e2bf3c9332c6305ef6

2017-04-25 09:53 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +					throw new AuthenticationFailedException("Authentication Failed, access token is not available");
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/9677bf19d79c461d484e61e2bf3c9332c6305ef6

2017-04-25 10:14 UTC, malakasilva approved these changes
fix all the comments and release the connetor

2017-04-25 10:14 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("IOException while reading the response from " + url, e);
Put a meaningful message.
eg: Error when reading the response from <url> to update user claims.

2017-04-25 10:47 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticator.java
> +			throw new ApplicationAuthenticatorException("IOException while reading the response from " + url, e);
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/1/commits/ddca573b64c6a6a1c7d9d8e270863e82ca9b77c9

2017-04-25 11:03 UTC, ruwanta approved these changes

2017-04-25 11:15 UTC, merged

2017-09-06 07:05 UTC, vives commented on pom.xml
> +            <url>http://maven.wso2.org/nexus/service/local/staging/deploy/maven2/</url>
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/4

2017-09-06 07:05 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/pinterest/PinterestAuthenticatorConstants.java
> +
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-pinterest/pull/4